CREATE TABLE users (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "email" text UNIQUE NOT NULL,
    "hashed_password" text NOT NULL,
    "created_at" timestamp NOT NULL,
    "banned" boolean NOT NULL,
    "deleted" boolean NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email ON users (email);